#!/bin/bash

export JANUSGRAPH_VERSION="${janusgraph.version}"
export JANUSGRAPH_PACKAGE="${janusgraph.package}"

export JANUSGRAPH_PARCEL=${PARCELS_ROOT}/${PARCEL_DIRNAME}
export JANUSGRAPH_HOME=${PARCELS_ROOT}/${PARCEL_DIRNAME}/${JANUSGRAPH_PACKAGE}

